spring:
  profiles:
    active: local
  datasource:
    url: jdbc:h2:tcp://localhost/~/fakestore
    username: cp
    password: young
    driver-class-name: org.h2.Driver


  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true